version: '3.8'

services:

  redis:
    image: redis:7-alpine
    container_name: leilao-redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - leilao-redis-data:/data
    networks:
      - leilao-network

volumes:
  leilao-db-data:
  leilao-redis-data:

networks:
  leilao-network: